use_frameworks!

target 'XLMediaPlayer_Example' do
  pod 'XLMediaPlayer', :path => '../'

  target 'XLMediaPlayer_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
